version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - REACT_APP_MONGO_URL=mongodb://mongo:27017/todo_db
    networks:
      - app-network

  frontend:
    build: .
    ports:
      - "3000:80"  # Serve frontend on port 3000 using Nginx
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: todo_db
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo_data:
